### PR TITLE
Add support for Python 3.9

### PR DESCRIPTION
**Pull request by jugmac00**
modified:   .travis.yml
modified:   CHANGES.rst
modified:   setup.py
modified:   tox.ini

### CODE REVIEW

**Review by dataflake — CHANGES_REQUESTED** [review]
Just slapping test configs for Python 3.9 onto a package that is still supposed to retain Zope 4 compatibility is not enough.

Please look at https://github.com/zopefoundation/Products.CMFCore/pull/99/files to get an idea how Michael changed the tox configuration so all those Python versions that are not supported in Zope 5 are tested with a separate small Zope 4 buildout.

**Comment by jugmac00** [comment]
> Just slapping test configs for Python 3.9 onto a package that is still supposed to retain Zope 4 compatibility is not enough.

My PR did not touch Zope 4 compatibility. The package still gets tested with Zope 4.

I came here to help with the bug report (#12), not to add Zope 5 compatibility tests.

As I noticed the package was lacking support for 3.9, I added it. That is how I understand my open source contribution. Spend a few minutes here and there.

I'd appreciate if general guidelines, as that we now test Zope 4 (products) with 2.7 and 3.5 only (contrary to our [roadmap](https://zope.readthedocs.io/en/latest/roadmap.html)), and Zope 5 (products) with 3.6, 3.7, 3.8 and 3.9, would be published somewhere, e.g. the meta repository or the mailing list.

That said I just updated `tox` analagous to @icemac's preparatory work. Thanks for that!

**Comment by dataflake** [comment]
"Adding Python 3.9 support" and leaving the remaining buildout configuration on Zope 4 makes no sense. Zope 4 does not have (and will not have) Python 3.9 compatibility. So adding Python 3.9 support requires adding Zope 5 test support.

Running the Travis tests on Zope 4 for Python 2.7 and 3.5 only is not "contrary to our roadmap". We are not dropping support for Zope 4 on any of the Python versions listed on the roadmap. This mixed Travis configuration represents a good compromise of testing on all Python versions without duplicating all tests for both Zope versions, which would make the Travis tests even slower.

As you can see from the PR I linked, Michael just came up with that method for a similar issue a few days ago. So no one has found the time to create some guidance, sorry. You are welcome to write such a document if you have time.

**Review by dataflake — APPROVED** [review]

**Comment by jugmac00** [comment]
Thanks for the review! (and the fixes)

**Pull request merged**
